project 'DangAn.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DangAn' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DangAn

  target 'DangAnTests' do
    inherit! :search_paths
pod 'FMDB'

  end

end
